name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Checkout current build target
      uses: actions/checkout@v2
      with:
        path: 'UnityStub-Vanguard'
    - name: Checkout RTCV peer dependency
      uses: actions/checkout@v2
      with:
        repository: 'redscientistlabs/RTCV'
        ref: '506'
        path: 'RTCV'
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Restore Nuget packages in RTCV
      run: msbuild /t:restore '.\RTCV\RTCV.sln'
    - name: Restore Nuget packages in UnityStub-Vanguard
      run: msbuild /t:restore '.\UnityStub-Vanguard\UnityStub-Vanguard.sln'
    - name: Build with MSBuild
      run: msbuild '.\UnityStub-Vanguard\UnityStub-Vanguard.sln'
